### PR TITLE
ci(github-action): run python check on both push and pull request

### PR DESCRIPTION
**Pull request by Lee-W**
(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)

## Types of changes
Please put an `x` in the box that applies

- [x] **Other (please describe)** run python check on both push and pull request

## Description
**Describe what the change is**

## Checklist:
- [ ] Add test cases to all the changes you introduce
- [x] Run `inv lint` locally to ensure all linter checks pass
- [x] Run `inv test` locally to ensure all test cases pass
- [x] Run `inv secure` locally to ensure no major vulnerability is introduced
- [x] Update the documentation if necessary

## Steps to Test This Pull Request
1. Send a pull request

## Expected behavior
The Python Check Github action should be run automatically

## Additional context
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by tai271828** [comment]
uh, thanks for this improvement. We have had this low hanging fruit for a while : D

**Review by tai271828 — APPROVED** [review]

**Comment by tai271828** [comment]
@Lee-W maybe next you may create a pull request from your forked repository rather than the branch of pycontw-postevent-report-generator repository. Do you think it is a good idea?

**Comment by tai271828** [comment]
@Lee-W  fyi, if you need to manipulate several remote repositories via git, you may use `git remote add <remote repo url` to trace several remote repository under the same local copy.

**Comment by Lee-W** [comment]
@tai271828 Thanks for the tip 😄 I actually have a few remote repos locally haha.
I'm ok with creating a pull request from my forked repo, but I'm not sure I know the necessity to do so. As long as we're not pushing to the master branch and remember to truncate the stale branches, I think we're good to push directly to this repo. The benefit is reducing the burden of active contributors. But maybe there are concerns or issues I didn't notice. I'm open to discussion  🙂

**Comment by tai271828** [comment]
`remember to truncate the stale branches` is the failure point if there are several developers. However, there are currently only two people able to push to this repository (you and me), so feel free to do what you have done, and no big difference between two ways until more people able to push.

**Pull request merged**
