### PR TITLE
ci(github-action): fix auto versioning

### PR DESCRIPTION
**Pull request by Lee-W**

### CODE REVIEW

**Comment by Lee-W** [comment]
Hmmm... this time I try on my folk repo and succeeded. It should work now. 😨

**Comment by Lee-W** [comment]
I guess I know the reason why it's failed...  It detects whether the latest commit contains `bump`, and when we merge it. My branch name `fix-version-bump` blocks it....

**Comment by tai271828** [comment]
Fair point! Good job!

**Comment by Lee-W** [comment]
Anyway, I still have other interesting stuff to try. I might send another MR for the pre-commit tomorrow. And, we'll know whether my guess is correct then.

**Comment by tai271828** [comment]
I don't think this fix is urgent that much. If you want to focus on the other stuff, please feel free to go there first.

**Pull request merged**
