### PR TITLE
Add pre commit hook

### PR DESCRIPTION
**Pull request by Lee-W**
Since [the last commit of this pr](https://github.com/pycontw/pycontw-postevent-report-generator/commit/b7ebc46f43fb848d83121bc975ef991ed560935c) make a huge amount of style change, I would recommend skipping that commit and reviewing the commit before it.

### feat
- add commitizen pre-commit hook
- add isort into reformat and rename original black task as black_check
- add setup-pre-commit-hook task

### CODE REVIEW

**Comment by Lee-W** [comment]
We'll know whether auto versioning will work this time!

**Comment by Lee-W** [comment]
I do change the black configuration to 88 which is its default config. But the import order is unified by isort.

**Comment by Lee-W** [comment]
https://github.com/pycontw/pycontw-postevent-report-generator/actions/runs/51221703

It works!

**Comment by tai271828** [comment]
hooray!! looks like pre-commit hook works.

**Pull request merged**
